/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio2;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
         this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonA = new javax.swing.JButton();
        jButtonB = new javax.swing.JButton();
        jButtonDiferencia = new javax.swing.JButton();
        jButtonUnion = new javax.swing.JButton();
        jButtonInterseccion = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonA.setText("UNIVERSIDAD A");
        jButtonA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAActionPerformed(evt);
            }
        });

        jButtonB.setText("UNIVERSIDAD B");
        jButtonB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBActionPerformed(evt);
            }
        });

        jButtonDiferencia.setText("A - B");
        jButtonDiferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDiferenciaActionPerformed(evt);
            }
        });

        jButtonUnion.setText(" A ∪ B");
        jButtonUnion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUnionActionPerformed(evt);
            }
        });

        jButtonInterseccion.setText("A ∩ B");
        jButtonInterseccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInterseccionActionPerformed(evt);
            }
        });

        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENÚ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonDiferencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonUnion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonInterseccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonA, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(124, 124, 124))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonA, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonB, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonDiferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonUnion, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonInterseccion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAActionPerformed
        UniA uni = new UniA();
        uni.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonAActionPerformed

    private void jButtonBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBActionPerformed
        UniB unib = new UniB();
        unib.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBActionPerformed

    private void jButtonDiferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDiferenciaActionPerformed
        int op = 0;
         mouseHerramientaMisteriosa(op);

    }//GEN-LAST:event_jButtonDiferenciaActionPerformed

    private void jButtonUnionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUnionActionPerformed
        concatenar();
    }//GEN-LAST:event_jButtonUnionActionPerformed

    private void jButtonInterseccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInterseccionActionPerformed
        int op = 1;
        mouseHerramientaMisteriosa(op);
    }//GEN-LAST:event_jButtonInterseccionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed
 
    public static void mouseHerramientaMisteriosa(int op){
          FileReader frA = null;
          FileReader frB = null;
          int sw = 0;
          String lineR ="";
          try {
            File ficheroA = new File("universidadA.txt");
            frA = new FileReader(ficheroA);          
            BufferedReader brA = new BufferedReader(frA); 
            File ficheroB = new File("universidadB.txt");
            frB = new FileReader(ficheroB);          
            BufferedReader brB = new BufferedReader(frB);
               String line,line2;
            while (brA.ready()) {
            line = brA.readLine();            
            
                  while (brB.ready()) {
                      line2 = brB.readLine();                     
                        if (line2.equals(line)){
                            sw=1;                                                
                        }
                    }
                  brB.close();
                  frB.close();
                  frB = new FileReader(ficheroB);          
                  brB = new BufferedReader(frB);  
                  
                  if(sw==1 && op == 0){
                          lineR = lineR +"\n"+line;
                      }
                  
                  if(sw==0 && op == 1){                                
                             lineR = lineR + "\n"+line;                                                                       
                  }
            }
            
        } catch (Exception e) {
           JOptionPane.showMessageDialog(null, e.getMessage());
        } finally {
            try {
                if (frA != null) {
                    frA.close();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
         
          JOptionPane.showMessageDialog(null,lineR);
           
    }
  
  
       
     public void concatenar() {  
        FileReader fr = null;
        FileReader frB = null;  
        try {
            File fichero = new File("universidadA.txt");
            File ficheroB = new File("universidadB.txt");
            fr = new FileReader(fichero);
            frB = new FileReader(ficheroB);
            BufferedReader br = new BufferedReader(fr);
            BufferedReader brB = new BufferedReader(frB);
            leerFichero(br,brB);
       
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } finally {
            try {
                if (fr != null) {
                    fr.close();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
 
    }
 public  void leerFichero(BufferedReader br, BufferedReader brB ) throws Exception {
      
        String linea,lineab,linea2="";
        linea = br.readLine();
        while (linea != null) {
            linea2 = linea2+"\n"+linea;
        
            linea=br.readLine();
        }
        lineab = brB.readLine();
        while (lineab != null) {
            linea2 = linea2+"\n"+lineab;
            lineab=brB.readLine();
        }
       JOptionPane.showMessageDialog(null, linea2);
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonA;
    private javax.swing.JButton jButtonB;
    private javax.swing.JButton jButtonDiferencia;
    private javax.swing.JButton jButtonInterseccion;
    private javax.swing.JButton jButtonUnion;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
