/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio2;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class UniA extends javax.swing.JFrame {

    /**
     * Creates new form UniA
     */
    public UniA() {
        initComponents();
         this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButtonEdad = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("UNIVERSIDAD A");

        jButton1.setText("AÑADIR ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("MOSTRAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("VOLVER A MENU");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButtonEdad.setText("SEPARAR POR EDAD");
        jButtonEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEdadActionPerformed(evt);
            }
        });

        jButton5.setText("SEPARAR POR SEXO ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonEdad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButtonEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Añadira a = new Añadira();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed
public static void mostrarFichero() {
  
        FileReader fr = null;
        try {
            File fichero = new File("universidadA.txt");
            fr = new FileReader(fichero);
            BufferedReader br = new BufferedReader(fr);
            leerFichero(br);
        } catch (Exception e) {
           JOptionPane.showMessageDialog(null, e.getMessage());
        } finally {
            try {
                if (fr != null) {
                    fr.close();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
 
    }
 public static void leerFichero(BufferedReader br) throws Exception {
      
        String linea, linea2="";
        linea = br.readLine();
        while (linea != null) {
            linea2 = linea2+"\n"+linea;
            linea=br.readLine();
            
 
        }
        
        JOptionPane.showMessageDialog(null,linea2);
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       FileReader fr = null;
        mostrarFichero();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        MenuPrincipal m = new MenuPrincipal();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEdadActionPerformed
        
        int op = 0;
        File f1 = new File("MayoresA.txt");
        File f2 = new File("menoresA.txt");
        if(f1.exists()) {
                f1.delete();
                f2.delete();
                mouseHerramientaMisteriosa(op, "MayoresA", "menoresA");
            }
            else{
              mouseHerramientaMisteriosa(op, "MayoresA", "menoresA");
           }
        
       
    }//GEN-LAST:event_jButtonEdadActionPerformed

public static void mouseHerramientaMisteriosa(int op, String busqueda1, String busqueda2){
          FileReader frA = null;
          FileWriter fw1 = null, fw2 = null;
          
          try {
            //abro el archivo de MayoresA para escritura
            fw1 = new FileWriter(busqueda1 + ".txt");
            BufferedWriter bw1 = new BufferedWriter(fw1);
            PrintWriter pw1 = new PrintWriter(bw1);
            
            //abro el archivo de menoresA para escritura
            fw2 = new FileWriter(busqueda2 + ".txt");
            BufferedWriter bw2 = new BufferedWriter(fw2);
            PrintWriter pw2 = new PrintWriter(bw2);
            
            //abro el archivo de universidadA para lectura
            File ficheroA = new File("universidadA.txt");
            frA = new FileReader(ficheroA);         
            BufferedReader brA = new BufferedReader(frA); 
            
            String line, line1 = "", line2 = "";
            
            while (brA.ready()) {
            line = brA.readLine();
            String [] registro = line.split(", ");
  
              if(op ==0){
                 if (Integer.parseInt(registro[4])>= 18){                  
                   pw1.print(line);
                   pw1.println();
                   line1 = line1 +"\n"+line;
                 }
                 if(Integer.parseInt(registro[4]) < 18){ 
                   pw2.print(line);
                   pw2.println(); 
                   line2 = line2 +"\n"+line;
                 } 
             }
             if (op == 1){ 
                 if(registro[3].equals("femenino")){
                     
                     pw1.print(line);
                     pw1.println();
                     line1 = line1 +"\n"+line;
                 }
                 if(registro[3].equals("masculino")){
                     pw2.print(line);
                     pw2.println();
                     line2 = line2 +"\n"+line;
                 }
                 
             }
            }
             
                    pw1.close();
                    bw1.close();
                    fw1.close();
                    pw2.close();
                    bw2.close();
                    fw2.close();
                    
                    if (op == 0){
                        JOptionPane.showMessageDialog(null,"MAYORES DE EDAD"+ "\n" +line1); 
                        JOptionPane.showMessageDialog(null,"MENORES DE EDAD"+"\n"+line2);
                    }else{
                        JOptionPane.showMessageDialog(null,"SEXO FEMENINO"+ "\n" +line1); 
                        JOptionPane.showMessageDialog(null,"SEXO MASCULINO"+"\n"+line2);
                    }
                        
        } catch (Exception e) {
           JOptionPane.showMessageDialog(null, e.getMessage());
        } finally {
            try {
                if (frA != null) {
                    frA.close();
                }
              
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
       
    }    

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int op = 1;
        File f3 = new File("femeninoA.txt");
        File f4 = new File("masculinoA.txt");
        if(f3.exists()) {
                f3.delete();
                f4.delete();
                mouseHerramientaMisteriosa(op, "femeninoA", "masculinoA");
            }
            else{
              mouseHerramientaMisteriosa(op, "femeninoA", "masculinoA");
           }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonEdad;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
